name: Continous Integration

on:
  push:
    branches:
      [master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: list code
        run: ls

      - name: build
        run: echo "build"


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test
        run: echo "test"


  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: release
        run: echo "release"